In [46]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import norm, ttest_ind

from statsmodels.stats.weightstats import ztest

In [4]:
df_team_1 = pd.read_csv("team_1.csv")
df_team_1.head()

sales
0   1853
1   1956
2   1837
3   1885
4   1755

In [5]:
df_team_1.shape

(50, 1)

In [6]:
df_team_1.mean()

sales    1850.02
dtype: float64

In [7]:
df_team_1.std()

sales    86.283465
dtype: float64

##### H0: mu = 1800 
##### H1: mu > 1800

In [8]:
sales = df_team_1["sales"]

In [9]:
ztest(sales, value = 1800, alternative = "larger") # right tail test

(4.099218918585183, 2.0727339284021037e-05)

In [10]:
# (test statistic, p_value)

In [11]:
z_stat = (sales.mean() - 1800)/(sales.std() / np.sqrt(50))
z_stat

4.099218918585183

In [12]:
1 - norm.cdf(z_stat)

2.0727339284043467e-05

### Two drug example:

In [14]:
d1 = pd.read_csv("drug_1_recovery.csv")
d2 = pd.read_csv("drug_2_recovery.csv")

In [15]:
d1

drug_1
0   8.824208
1   7.477745
2   7.557121
3   7.981314
4   6.827716
..       ...
95  6.890506
96  7.725759
97  6.848016
98  7.969997
99  7.104209

[100 rows x 1 columns]

In [16]:
d2

drug_2
0    9.565974
1    7.492915
2    8.738418
3    7.635235
4    4.125593
..        ...
115  7.861993
116  8.233510
117  5.876257
118  7.789454
119  8.836125

[120 rows x 1 columns]

In [17]:
d1.mean()

drug_1    7.104917
dtype: float64

In [18]:
d2.mean()

drug_2    8.073423
dtype: float64

In [19]:
# H0 : m1 = m2
# HA : m1 != m2

ztest(d1, d2, value = 0) # two tail test

(array([-5.32112438]), array([1.03127863e-07]))

In [20]:
# H0 : m1 = m2
# HA : m1 < m2 
    
ztest(d1, d2, value = 0, alternative= "smaller") # left tail test

(array([-5.32112438]), array([5.15639315e-08]))

In [21]:
# H0 : m1 = m2  - not able to reject False H0
# HA : m1 > m2

ztest(d1, d2, value = 0, alternative= "larger")

(array([-5.32112438]), array([0.99999995]))

### Youtube Test data

In [23]:
youtube_data = pd.read_csv("youtube.csv")
youtube_data.sample(100)

date  customer_id  premium  watch_time_hrs customer_segmnt
6178   2018-10-18          550        1        2.867761       treatment
15172  2018-09-01          527        0        3.165855       treatment
10354  2018-06-08          508        0        3.305207       treatment
15973  2018-12-27          484        0        1.963448         control
5227   2018-07-20          537        0        3.592499       treatment
...           ...          ...      ...             ...             ...
19545  2018-01-19          967        0        1.454415       treatment
9134   2018-02-18           30        0        1.150701         control
1871   2018-12-02          578        1        2.252185       treatment
7000   2018-10-20          466        0        2.421825         control
17039  2018-06-04          116        0        6.241765         control

[100 rows x 5 columns]

In [24]:
youtube_data.shape

(20000, 5)

In [25]:
youtube_data.customer_segmnt.value_counts()

control      10000
treatment    10000
Name: customer_segmnt, dtype: int64

In [27]:
youtube_data["watch_time_hrs"].describe()

count    20000.000000
mean         9.362542
std        244.884839
min          0.160268
25%          1.678066
50%          2.670953
75%          4.204673
max      10007.648185
Name: watch_time_hrs, dtype: float64

In [31]:
q_998 = youtube_data["watch_time_hrs"].quantile(0.998)
q_998

21.356607722117484

In [33]:
youtube_data_no_out = youtube_data[youtube_data["watch_time_hrs"] < q_998]

In [35]:
youtube_data_no_out.shape

(19960, 5)

In [36]:
youtube_data_no_out["watch_time_hrs"].describe()

count    19960.000000
mean         3.331932
std          2.474943
min          0.160268
25%          1.676373
50%          2.664286
75%          4.186733
max         21.356119
Name: watch_time_hrs, dtype: float64

In [37]:
control_data = youtube_data_no_out[youtube_data_no_out["customer_segmnt"] == "control"]
treatment_data = youtube_data_no_out[youtube_data_no_out["customer_segmnt"] == "treatment"]

In [38]:
control_data.shape

(9973, 5)

In [40]:
treatment_data.shape

(9987, 5)

In [42]:
control_data['watch_time_hrs'].mean()

3.6099602285795642

In [43]:
treatment_data['watch_time_hrs'].mean()

3.054293679735035

In [44]:
## Two tail test
# H0 : m1 = m2
# HA : m1 != m2

ztest(control_data["watch_time_hrs"], treatment_data["watch_time_hrs"])

# SS diff, reject H0

(15.96034913022092, 2.4137738128170024e-57)

In [47]:
# This is called T-test. But since "n1" and "n2" are large, we get similar results
ttest_ind(control_data["watch_time_hrs"], treatment_data["watch_time_hrs"])

Ttest_indResult(statistic=15.96034913022092, pvalue=5.438408586231319e-57)

In [45]:
## Right tail test
# H0 : m1 = m2
# HA : m1 > m2 

ztest(control_data["watch_time_hrs"],
      treatment_data["watch_time_hrs"],
     alternative="larger")

# Statistically Signifance result diff, avg watch time is declining 
# reject H0 

(15.96034913022092, 1.2068869064085012e-57)